### ISSUE TITLE
Follow SMACSS guidelines

### ISSUE THREAD

**Issue by andrewmerrell** [sky-uk/nowtv-toolkit#1]
We don't appear to be adopting a CSS guideline within this repository, we seem to somewhat be using the naming convention of bootstrap.

I suggest following SMACSS, it's the guidelines we used to create the css on the global navigation. I started to migrate things across and have given a little example layout on branch smacssify-toolkit (commit: 20f6413d9f8deff83c65a9f2aa62fcd8cf76d2e3)

I have created a bunch of abstract classes and am using that within the main component itself, if you npm in the styles you can choose to take the abstract or use the named classes - as we discussed in the last tech get together when we spoke about splitting out from react, best of both worlds.

I've also started to create a style-guide set of folders, at the moment only created global, but suggest we create a signup, account and help, etc... type style guide, with basic info on how to create or layout 'default' styling. Obviously design in the area will be specific however it should create a good reference guide.

Similar to the BBC GEL http://www.bbc.co.uk/gel/guidelines/category/foundations

Other inspiration:
http://rizzo.lonelyplanet.com/styleguide/design-elements/colours
https://www.google.com/design/spec/material-design/introduction.html

**Comment by georgerichmond** [comment]
the lonely planet one is really nice
