### ISSUE TITLE
Input placeholder will not work on IE9 and below or Opera Mini

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-toolkit#5]

**Comment by ariley90** [comment]
I've tested on IE8 and the inputs on the docs are functional. The text isn't quite vertically align to be centre within the input but not sure if that's an issue with older browsers.

**Comment by peter-mouland** [comment]
There is no mention of browser support in any docs in this repo.

Would be good to get clarification on what is meant to be actively supported.

I would suggest that ie9 and below should be functional, not perfect.

**Comment by peter-mouland** [comment]
I'm going to close this as those browsers are not supported.
If anyone does need to support those browsers feel free to submit a PR
